- Terraform Static Analysis

diff --git a/.github/workflows/terraform-static-analysis.yml b/.github/workflows/terraform-static-analysis.yml
--- a/.github/workflows/terraform-static-analysis.yml
+++ b/.github/workflows/terraform-static-analysis.yml
@@ -80,7 +80,7 @@ jobs:
 
   tflint:
     name: TFLint
-    if: github.event_name == 'pull_request'
+    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
     runs-on: ubuntu-latest
     needs: terraform-format-validate
 
@@ -92,30 +92,30 @@ jobs:
       - name: Set Environment
         run: |
           if [ "${{ github.event_name }}" == "pull_request" ]; then
-              BRANCH="${{ github.base_ref }}"
-            else
-              BRANCH="${{ github.ref_name }}"
-            fi
+                BRANCH="${{ github.base_ref }}"
+              else
+                BRANCH="${{ github.ref_name }}"
+              fi
 
-            case "$BRANCH" in
-              dev)
-                ENV=dev
-                ;;
-              staging)
-                ENV=staging
-                ;;
-              main)
-                ENV=production
-                ;;
-              *)
-                echo "Invalid Target Branch: $BRANCH"
-                exit 1
-                ;;
-            esac
+              case "$BRANCH" in
+                dev)
+                  ENV=dev
+                  ;;
+                staging)
+                  ENV=staging
+                  ;;
+                main)
+                  ENV=production
+                  ;;
+                *)
+                  echo "Invalid Target Branch: $BRANCH"
+                  exit 1
+                  ;;
+              esac
 
-            echo "ENV=$ENV" >> $GITHUB_ENV
-            echo "TFVARS_FILE=environments/$ENV/$ENV.tfvars" >> $GITHUB_ENV
-            echo "Using TFVARS file: environments/$ENV/$ENV.tfvars"
+              echo "ENV=$ENV" >> $GITHUB_ENV
+              echo "TFVARS_FILE=environments/$ENV/$ENV.tfvars" >> $GITHUB_ENV
+              echo "Using TFVARS file: environments/$ENV/$ENV.tfvars"
 
         # Terraform
       - name: Setup Terraform
@@ -165,7 +165,7 @@ jobs:
         run: tflint --recursive -f compact || true
 
   checkov-security-analysis:
-    if: github.event_name == 'pull_request'
+    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
     name: Checkov Security Analysis
     runs-on: ubuntu-latest
     needs: tflint
