- Backend BootStrap

diff --git a/.github/workflows/terraform-backend-bootstrap.yml b/.github/workflows/terraform-backend-bootstrap.yml
--- a/.github/workflows/terraform-backend-bootstrap.yml
+++ b/.github/workflows/terraform-backend-bootstrap.yml
@@ -16,56 +16,55 @@ jobs:
       - name: Checkout Repo
         uses: actions/checkout@v4
 
+      # List Modules
       - name: List Module Folders
         run: ls -l Modules/
 
-      - name: Confirm Environments File
-        run: ls -l environments/backend/backend.tfvars
+      # Confirmed Back End File
+      - name: Confirm Backend Environment File
+        run: |
+          ENV_FILE=environments/backend/backend.tfvars
+          if [ ! -f "$ENV_FILE" ]; then
+            echo "Backend TFVARS File Missing"
+            exit 1
+          fi
+          echo "Found Backend.tfvars"
 
-      - name: Clean Terraform Cache - Resource Group
-        working-directory: Modules/Resource-Group
+        # Clear Terraform Cache
+      - name: Clean Terraform Cache
+        working-directory: environments/backend
         run: |
           find . -name ".terraform" -type d -exec rm -rf {} +
           rm -f .terraform.lock.hcl tfplan
 
-      - name: Clean Terraform Cache - Storage
-        working-directory: Modules/Storage
-        run: |
-          find . -name ".terraform" -type d -exec rm -rf {} +
-          rm -f .terraform.lock.hcl tfplan
-
-      # Terraform
+      # Terraform Setup
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v2
         with:
           terraform_version: latest
 
+      # Terraform Version
       - name: Terraform Version
         run: terraform version
 
-      # Terraform Init - Resource Group
-      - name: Initialize Resource Group
-        working-directory: Modules/Resource-Group
+      # Terraform Init - Backend
+      - name: Initialize Terraform Backend
+        working-directory: environments/backend
         run: terraform init
 
-      # Terraform Init - Storage
-      - name: Initialize Storage Module
-        working-directory: Modules/Storage
-        run: terraform init
-
-      # Terraform Plan - Resource Group
-      - name: Terraform Plan Resource Group
-        working-directory: Modules/Resource-Group
-        run: terraform plan -var-file=../../environments/backend/backend.tfvars -out=tfplan
+      # Terraform Plan - Backend
+      - name: Terraform Plan Backend Resources
+        working-directory: environments/backend
+        run: terraform plan -var-file=backend.tfvars -out=tfplan
         env:
           ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
           ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
           ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
           ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
 
-      # Terraform Apply - Resource Group
-      - name: Terraform Apply Resource Group
-        working-directory: Modules/Resource-Group
+      # Terraform Apply - Backend
+      - name: Terraform Apply Backend
+        working-directory: environments/backend
         run: terraform apply -auto-approve tfplan
         env:
           ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
@@ -73,25 +72,22 @@ jobs:
           ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
           ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
 
-      # Terraform Plan - Storage
-      - name: Terraform Plan Storage
-        working-directory: Modules/Storage
-        run: terraform plan -var-file=../../environments/backend/backend.tfvars -out=tfplan
-        env:
-          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
-          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
-          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+      # Confirm State File In Directory
+      - name: Confirm Local Terraform State File
+        run: |
+          STATE_FILE=environments/backend/terraform.tfstate
+          if [ ! -f "$STATE_FILE" ]; then
+            echo "Local Terraform State File Missing!"
+            exit 1
+          fi
+          echo "Found Local Terraform State - $STATE_FILE"
 
-      # Terraform Apply - Storage
-      - name: Terraform Apply Storage
-        working-directory: Modules/Storage
-        run: terraform apply -auto-approve tfplan
-        env:
-          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
-          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
-          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+      # Upload Local State For Workflow
+      - name: Upload Local Terraform State
+        uses: actions/upload-artifact@v3
+        with:
+          name: terraform-backend-state
+          path: environments/backend/terraform.tfstate
 
   Storage-RBAC:
     name: Storage RBAC
@@ -101,6 +97,7 @@ jobs:
       - name: Checkout Repo
         uses: actions/checkout@v4
 
+      # Confirmed Back End File
       - name: Confirm Environments File
         run: ls -l environments/backend/backend.tfvars
 
@@ -137,7 +134,7 @@ jobs:
           az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
         # Wait Storage Account
-      - name: Wait for Storage Account
+      - name: Waiting For Storage To Provision..
         run: |
           echo -n "Waiting For Storage Account '${{ env.STORAGE_ACCOUNT_NAME }}'..."
           until az storage account show --name "${{ env.STORAGE_ACCOUNT_NAME }}" --resource-group "${{ env.RG_NAME }}" >/dev/null 2>&1; do
@@ -156,7 +153,7 @@ jobs:
             >/dev/null 2>&1
           echo "Role 'Owner' Assigned To SP Successfully."
 
-        # Assign Storage Blob Data Contributo RBAC
+        # Assign Storage Blob Data Contributor RBAC
       - name: Assign SP RBAC - Storage Blob Data Contributor
         run: |
           az role assignment create \
@@ -178,14 +175,37 @@ jobs:
       - name: Checkout Repo
         uses: actions/checkout@v4
 
+      # Download Local State
+      - name: Download Local Terraform State
+        uses: actions/download-artifact@v3
+        with:
+          name: terraform-backend-state
+          path: environments/backend/
+
+      # Confirm State File In Directory
+      - name: Confirm Local Terraform State File
+        run: |
+          STATE_FILE=environments/backend/terraform.tfstate
+          if [ ! -f "$STATE_FILE" ]; then
+            echo "Local Terraform State File Missing!"
+            exit 1
+          fi
+          echo "Found Local Terraform State - $STATE_FILE"
+
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v2
         with:
           terraform_version: latest
 
-        # Confirm ENV
-      - name: Confirm Environments File
-        run: ls -l environments/backend/backend.tfvars
+        # Confirm Backend File
+      - name: Confirm Backend Environment File
+        run: |
+          ENV_FILE=environments/backend/backend.tfvars
+          if [ ! -f "$ENV_FILE" ]; then
+            echo "Backend TFVARS File Missing"
+            exit 1
+          fi
+          echo "Found Backend.tfvars"
 
         # Load Backend Variables
       - name: Load Backend Variables
@@ -213,9 +233,9 @@ jobs:
           echo "STORAGE_CONTAINER_NAME=$STORAGE_CONTAINER_NAME"
           echo "STATE_KEY=$STATE_KEY"
 
-        # Terraform Init - Resource-Group - Migrate State
-      - name: Initialize Terraform - Resource-Group - Migrate State
-        working-directory: Modules/Resource-Group
+        # Terraform Init - Backend - Migrate State
+      - name: Initialize Terraform Backend - Migrate Local State
+        working-directory: environments/backend
         env:
           ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
           ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
@@ -226,33 +246,8 @@ jobs:
           -backend-config="resource_group_name=${{ env.RG_NAME }}" \
           -backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" \
           -backend-config="container_name=${{ env.STORAGE_CONTAINER_NAME }}" \
-          -backend-config="key=${{ env.STATE_KEY }}"
-
-          terraform init -migrate-state \
-          -backend-config="resource_group_name=${{ env.RG_NAME }}" \
-          -backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" \
-          -backend-config="container_name=${{ env.STORAGE_CONTAINER_NAME }}" \
-          -backend-config="key=${{ env.STATE_KEY }}"
-
-      - name: Initialize Terraform - Storage - Migrate State
-        working-directory: Modules/Storage
-        env:
-          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
-          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
-          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-        run: |
-          terraform init \
-          -backend-config="resource_group_name=${{ env.RG_NAME }}" \
-          -backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" \
-          -backend-config="container_name=${{ env.STORAGE_CONTAINER_NAME }}" \
-          -backend-config="key=${{ env.STATE_KEY }}"
-
-          terraform init -migrate-state \
-          -backend-config="resource_group_name=${{ env.RG_NAME }}" \
-          -backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" \
-          -backend-config="container_name=${{ env.STORAGE_CONTAINER_NAME }}" \
-          -backend-config="key=${{ env.STATE_KEY }}"
+          -backend-config="key=${{ env.STATE_KEY }}" \
+          -migrate-state
 
   trigger-production-deployment:
     name: Trigger Production Deployment
