- Terraform Backend Check; Skip Checks If RG Missing

diff --git a/.github/workflows/terraform-backend-check.yml b/.github/workflows/terraform-backend-check.yml
--- a/.github/workflows/terraform-backend-check.yml
+++ b/.github/workflows/terraform-backend-check.yml
@@ -132,48 +132,58 @@ jobs:
 
           backend_exists=true
 
-          # Storage Account
-          echo "Checking Storage Account..."
-          if ! az storage account show \
-            --name "$STORAGE_ACCOUNT_NAME" \
-            --resource-group "$RG_NAME" \
-            --output none; then
-              echo "Storage Account Missing"
+          # Resource Group
+          echo "Checking Resource Group..."
+          if ! az group show \
+           --name "$RG_NAME" \
+           --output none; then
+              echo "Resource Group '$RG_NAME' Missing"
               backend_exists=false
-          fi
-
-          # Container
-          echo "Checking Container..."
-          if ! az storage container show \
-            --name "$STORAGE_CONTAINER_NAME" \
-            --account-name "$STORAGE_ACCOUNT_NAME" \
-            --auth-mode login \
-            --output none; then
-              echo "Container Missing"
-              backend_exists=false
-          fi  
-
-          # State Key
-          echo "Checking State Key..."
-          set +e
-          BLOB_EXISTS=$(az storage blob exists \
-            --container-name "$STORAGE_CONTAINER_NAME" \
-            --name "$STATE_KEY" \
-            --account-name "$STORAGE_ACCOUNT_NAME" \
-            --auth-mode login \
-            --query exists \
-            --output tsv 2>/dev/null)
-
-          if [[ "$BLOB_EXISTS" != "true" ]]; then
-            echo "Backend Missing"
-            backend_exists=false
+              echo "Skipping Further Checks.."
           else
-            echo "Backend Exists"
-          fi
+            echo "Resource Group Exists"
 
-          echo "Backend Exists: $backend_exists"
+            # Storage Account
+            echo "Checking Storage Account..."
+            if ! az storage account show \
+              --name "$STORAGE_ACCOUNT_NAME" \
+              --resource-group "$RG_NAME" \
+              --output none; then
+                echo "Storage Account Missing"
+                backend_exists=false
+            fi
 
-          # Set Output For Triggers
+            # Container
+            echo "Checking Container..."
+            if ! az storage container show \
+              --name "$STORAGE_CONTAINER_NAME" \
+              --account-name "$STORAGE_ACCOUNT_NAME" \
+              --auth-mode login \
+              --output none; then
+                echo "Container Missing"
+                backend_exists=false
+            fi  
+
+            # State Key
+            echo "Checking State Key..."
+            set +e
+            BLOB_EXISTS=$(az storage blob exists \
+              --container-name "$STORAGE_CONTAINER_NAME" \
+              --name "$STATE_KEY" \
+              --account-name "$STORAGE_ACCOUNT_NAME" \
+              --auth-mode login \
+              --query exists \
+              --output tsv 2>/dev/null)
+
+            if [[ "$BLOB_EXISTS" != "true" ]]; then
+              echo "Backend Missing"
+              backend_exists=false
+            else
+              echo "Backend Exists"
+            fi
+            echo "Backend Exists: $backend_exists"
+
+           # Set Output For Triggers
           echo "::set-output name=backend_exists::$backend_exists"
           echo "backend_exists=$backend_exists" >> $GITHUB_ENV
 
