- Setup Workflow Triggers

diff --git a/.github/workflows/terraform-plan-validation.yml b/.github/workflows/terraform-plan-validation.yml
--- a/.github/workflows/terraform-plan-validation.yml
+++ b/.github/workflows/terraform-plan-validation.yml
@@ -2,50 +2,55 @@ name: Terraform Plan Validation
 
 on:
   workflow_dispatch:
-  workflow_run:
-    workflows: ["Terraform Static Analysis"]
-    types:
-      - completed
 
 jobs:
   Terraform-Plan-Validation:
-    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
     runs-on: ubuntu-latest
+    outputs:
+      env_name: ${{ steps.set-env.outputs.env }}
 
     steps:
       - name: Checkout Repo
         uses: actions/checkout@v4
 
       # Determine Environment & TFVARS File Based On Branch That Static Analsis Ran On - Workflow Dispatch
-      - name: Determine Environment
+      - name: Determine Branch Environment
         run: |
-          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
-            BRANCH="${{ github.ref_name }}"
-          else
-            BRANCH="${{ github.event.workflow_run.head_branch }}"
-          fi
+          if [ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]; then
+             BRANCH="${GITHUB_REF#refs/heads/}"
+           else
+             BRANCH="${{ github.event.workflow_run.head_branch }}"
+           fi
 
-          case "$BRANCH" in
-            dev)
-              ENV="dev"
-              ;;
-            staging)
-              ENV="staging"
-              ;;
-            main)
-              ENV="production"
-              ;;
-            *)
-              echo "Invalid Target Branch: $BRANCH"
-              exit 1
-              ;;
-          esac
+           case "$BRANCH" in
+             dev)
+               ENV="dev"
+               ;;
+             staging)
+               ENV="staging"
+               ;;
+             main)
+               ENV="production"
+               ;;
+             *)
+               echo "Invalid Target Branch: $BRANCH"
+               exit 1
+               ;;
+           esac
 
-          echo "ENV=$ENV" >> $GITHUB_ENV
-          echo "TFVARS_FILE=environments/${ENV}/${ENV}.tfvars" >> $GITHUB_ENV
-          echo "Using TFVARS File: environments/${ENV}/${ENV}.tfvars"
+           echo "ENV=$ENV" >> $GITHUB_ENV
+           echo "TFVARS_FILE=environments/${ENV}/backend.tfvars" >> $GITHUB_ENV
+           echo "Environment Detected: $ENV"
+           echo "Using TFVARS File: environments/${ENV}/backend.tfvars"
 
-      # Confirm TFVARS exists
+        # Set Environment Output
+      - name: Set Environment Output
+        id: set-env
+        run: |
+          echo "Environment Detected: $ENV"
+          echo "env=${ENV}" >> $GITHUB_OUTPUT
+
+        # Confirm Backend exists
       - name: Confirm TFVARS File
         run: |
           if [ ! -f "${{ env.TFVARS_FILE }}" ]; then
@@ -110,3 +115,24 @@ jobs:
           ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
           ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
           ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+
+  trigger-backend-check:
+    name: Trigger Backend Check
+    runs-on: ubuntu-latest
+    needs: Terraform-Plan-Validation
+
+    env:
+      ENV: ${{ needs.Terraform-Plan-Validation.outputs.env_name }}
+
+    steps:
+      - name: Trigger Terraform Plan Validation Workflow
+        uses: actions/github-script@v6
+        with:
+          github-token: ${{ secrets.PAT_TOKEN }}
+          script: |
+            await github.rest.actions.createWorkflowDispatch({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              workflow_id: "terraform-backend-check.yml",
+              ref: context.ref,
+            });
