- Backend

diff --git a/.github/workflows/terraform-backend-bootstrap.yml b/.github/workflows/terraform-backend-bootstrap.yml
--- a/.github/workflows/terraform-backend-bootstrap.yml
+++ b/.github/workflows/terraform-backend-bootstrap.yml
@@ -73,7 +73,7 @@ jobs:
           ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
           ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
 
-      # Confirm State File In Directory
+      # Confirm State File In Boot Strap Folder
       - name: Confirm Local Terraform State File
         run: |
           STATE_FILE=environments/backend/bootstrap/terraform.tfstate
@@ -83,17 +83,73 @@ jobs:
           fi
           echo "Found Local Terraform State - $STATE_FILE"
 
-      # Upload Local State To Migrate
-      - name: Upload Local Terraform State
+        # Copy Local State Into Backend Folder
+      - name: Copy Local State to Backend Folder
         run: |
-          STATE_DIR=environments/backend/bootstrap
-          STATE_FILE=$STATE_DIR/terraform.tfstate
+          cp environments/backend/bootstrap/terraform.tfstate \
+            environments/backend/backend/terraform.tfstate
+
+        # Confirm State File In Backend Folder
+      - name: Confirm Local State In Backend Folder
+        run: |
+          STATE_FILE=environments/backend/terraform.tfstate
           if [ ! -f "$STATE_FILE" ]; then
-            echo "Terraform Local State Missing"
+            echo "Local Terraform State File Missing!"
             exit 1
           fi
-          npx upload-artifact terraform-backend-state -p "$STATE_DIR" >/dev/null 2>&1 || exit 1
-          echo "Terraform Local State Uploaded Successfully"
+          echo "Found Local Terraform State - $STATE_FILE"
+
+        # Confirm Backend File
+      - name: Confirm Backend Environment File
+        run: |
+          ENV_FILE=environments/backend/backend.tfvars
+          if [ ! -f "$ENV_FILE" ]; then
+            echo "Backend TFVARS File Missing"
+            exit 1
+          fi
+          echo "Found Backend.tfvars"
+
+        # Load Backend Variables
+      - name: Load Backend Variables
+        run: |
+          RG=$(grep -E '^resource_group_name' environments/backend/backend.tfvars | awk -F'=' '{print $2}' | xargs)
+          SA=$(grep -E '^storage_account_name' environments/backend/backend.tfvars | awk -F'=' '{print $2}' | xargs)
+          CONTAINER=$(grep -E '^storage_container_name' environments/backend/backend.tfvars | awk -F'=' '{print $2}' | xargs)
+          KEY=$(grep -E '^state_key' environments/backend/backend.tfvars | awk -F'=' '{print $2}' | xargs)
+
+          RG="${RG//$'\r'/}"
+          SA="${SA//$'\r'/}"
+          CONTAINER="${CONTAINER//$'\r'/}"
+          KEY="${KEY//$'\r'/}"
+
+          echo "RG_NAME=$RG" >> $GITHUB_ENV
+          echo "STORAGE_ACCOUNT_NAME=$SA" >> $GITHUB_ENV
+          echo "STORAGE_CONTAINER_NAME=$CONTAINER" >> $GITHUB_ENV
+          echo "STATE_KEY=$KEY" >> $GITHUB_ENV
+
+        # Confirm Backend Variables
+      - name: Confirm Backend Variables
+        run: |
+          echo "resource_group_name=$RG_NAME"
+          echo "STORAGE_ACCOUNT_NAME=$STORAGE_ACCOUNT_NAME"
+          echo "STORAGE_CONTAINER_NAME=$STORAGE_CONTAINER_NAME"
+          echo "STATE_KEY=$STATE_KEY"
+
+        # Terraform Init - Backend - Migrate State
+      - name: Initialize Terraform Backend & Migrate Local State
+        working-directory: environments/backend
+        env:
+          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
+          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+        run: |
+          terraform init \
+          -backend-config="resource_group_name=${{ env.RG_NAME }}" \
+          -backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" \
+          -backend-config="container_name=${{ env.STORAGE_CONTAINER_NAME }}" \
+          -backend-config="key=${{ env.STATE_KEY }}" \
+          -migrate-state
 
   Storage-RBAC:
     name: Storage RBAC
@@ -180,13 +236,6 @@ jobs:
     steps:
       - name: Checkout Repo
         uses: actions/checkout@v4
-
-      # Download Local State
-      - name: Download Local Terraform State
-        run: |
-          mkdir -p environments/backend/bootstrap
-          npx download-artifact terraform-backend-state -p environments/backend >/dev/null 2>&1 || exit 1
-          echo "Terraform State Downloaded Successfully"
 
       # Confirm State File In Directory
       - name: Confirm Local Terraform State File
