- Terrafom Destroy; Updated Dynamic Envs

diff --git a/.github/workflows/terraform-destroy.yml b/.github/workflows/terraform-destroy.yml
--- a/.github/workflows/terraform-destroy.yml
+++ b/.github/workflows/terraform-destroy.yml
@@ -15,80 +15,146 @@ jobs:
       - name: List Module Folders
         run: ls -l Modules/
 
-      # Confirm Production TFvars Exists
-      - name: Confirm Production Environment File
+      # Determine Branch Based On Dispatch
+      - name: Determine Branch Environment & TFVARS Files
         run: |
-          ENV_FILE=environments/production/production.tfvars
-          if [ ! -f "$ENV_FILE" ]; then
-            echo "Production TFVARS File Missing"
-            exit 1
+          if [ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]; then
+            BRANCH="${GITHUB_REF#refs/heads/}"
+          else
+            BRANCH="${{ github.event.workflow_run.head_branch }}"
           fi
-          echo "Found Production.tfvars"
 
-      # Setup Terraform
+          case "$BRANCH" in
+            dev)
+              ENV="dev"
+              ;;
+            staging)
+              ENV="staging"
+              ;;
+            main)
+              ENV="production"
+              ;;
+            *)
+              echo "Invalid Target Branch: $BRANCH"
+              exit 1
+              ;;
+          esac
+
+          echo "ENV=$ENV" >> $GITHUB_ENV
+          echo "TFVARS_FILE=environments/${ENV}/${ENV}.tfvars" >> $GITHUB_ENV
+          echo "BACKEND_TFVARS_FILE=environments/${ENV}/backend.tfvars" >> $GITHUB_ENV
+
+          echo "Using TFVARS File: ${{ env.TFVARS_FILE }}"
+          echo "Using Backend TFVARS File: ${{ env.BACKEND_TFVARS_FILE }}"
+
+        # Set Environment Output
+      - name: Set Environment Output
+        id: set-env
+        run: |
+          echo "Environment Detected: $ENV"
+          echo "env=${ENV}" >> $GITHUB_OUTPUT
+          echo "tfvars_file=${TFVARS_FILE}" >> $GITHUB_OUTPUT
+          echo "backend_tfvars_file=${BACKEND_TFVARS_FILE}" >> $GITHUB_OUTPUT
+
+      # Confirm TFVARS Files Exist
+      - name: Confirm TFVARS Files
+        run: |
+          for f in "${{ env.TFVARS_FILE }}" "${{ env.BACKEND_TFVARS_FILE }}"; do
+            if [ ! -f "$f" ]; then
+              echo "Unable To Find: $f"
+              exit 1
+            fi
+            echo "Found: $f"
+          done
+
+        # Determine Branch Resouce Variables
+      - name: Determine Branch Resource Variables
+        run: |
+          BACKEND_FILE="environments/${ENV}/backend.tfvars"
+
+          if [ ! -f "$BACKEND_FILE" ]; then
+           echo "Backend TFVARS file not found: $BACKEND_FILE"
+           exit 1
+          fi
+
+           RG=$(grep -E '^resource_group_name' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
+           SA=$(grep -E '^storage_account_name' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
+           CONTAINER=$(grep -E '^storage_container_name' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
+           KEY=$(grep -E '^state_key_deployment' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
+
+           RG="${RG//$'\r'/}"
+           SA="${SA//$'\r'/}"
+           CONTAINER="${CONTAINER//$'\r'/}"
+           KEY="${KEY//$'\r'/}"
+
+           echo "RG_NAME=$RG" >> $GITHUB_ENV
+           echo "STORAGE_ACCOUNT_NAME=$SA" >> $GITHUB_ENV
+           echo "STORAGE_CONTAINER_NAME=$CONTAINER" >> $GITHUB_ENV
+           echo "STATE_KEY_DEPLOYMENT=$KEY" >> $GITHUB_ENV
+
+        # Confirm Backend Variables
+      - name: Confirm Backend Variables
+        run: |
+          echo "Resource Group Name       : ${{ env.RG_NAME }}"
+          echo "Storage Account Name      : ${{ env.STORAGE_ACCOUNT_NAME }}"
+          echo "Storage Container Name    : ${{ env.STORAGE_CONTAINER_NAME }}"
+          echo "Terraform Deployment State Key       : ${{ env.STATE_KEY_DEPLOYMENT }}"
+
+      # Clear Cahce
+      - name: Clear Cache
+        run: |
+          echo "Cleaning Cache..."
+
+          rm -rf .terraform
+          rm -f .terraform.lock.hcl
+
+          rm -rf environments/${ENV}/.terraform
+          rm -f environments/${ENV}/.terraform.lock.hcl
+
+          echo "Cleanup Complete"
+
+        # Setup Terraform
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v2
         with:
           terraform_version: latest
 
-      # Production Backend Variables
-      - name: Load Production Remote State Variables
-        run: |
-          RG=$(grep -E '^\s*resource_group_name\s*=' environments/production/production.tfvars | awk -F'=' '{print $2}' | xargs)
-          SA=$(grep -E '^\s*storage_account_name\s*=' environments/production/production.tfvars | awk -F'=' '{print $2}' | xargs)
-          CONTAINER=$(grep -E '^\s*storage_container_name\s*=' environments/production/production.tfvars | awk -F'=' '{print $2}' | xargs)
-          KEY=$(grep -E '^\s*state_key\s*=' environments/production/production.tfvars | awk -F'=' '{print $2}' | xargs)
-
-
-          RG="${RG//$'\r'/}"
-          SA="${SA//$'\r'/}"
-          CONTAINER="${CONTAINER//$'\r'/}"
-          KEY="${KEY//$'\r'/}"
-
-
-          echo "RG_NAME=$RG" >> $GITHUB_ENV
-          echo "STORAGE_ACCOUNT_NAME=$SA" >> $GITHUB_ENV
-          echo "STORAGE_CONTAINER_NAME=$CONTAINER" >> $GITHUB_ENV
-          echo "STATE_KEY=$KEY" >> $GITHUB_ENV
-
-        # Confirm Production Backend Variables
-      - name: Confirm Backend Variables Values
-        run: |
-          echo "resource_group_name=$RG_NAME"
-          echo "STORAGE_ACCOUNT_NAME=$STORAGE_ACCOUNT_NAME"
-          echo "STORAGE_CONTAINER_NAME=$STORAGE_CONTAINER_NAME"
-          echo "STATE_KEY=$STATE_KEY"
-
-      # Initialize Terraform Using Production State
-      - name: Initialize Production Terraform State
-        working-directory: environments/production
+      # Initialize Terraform Using Deployment State
+      - name: Initialize Deployment Terraform State
+        working-directory: .
         run: |
           terraform init -reconfigure \
             -backend-config="resource_group_name=${{ env.RG_NAME }}" \
             -backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" \
             -backend-config="container_name=${{ env.STORAGE_CONTAINER_NAME }}" \
-            -backend-config="key=${{ env.STATE_KEY }}" \
+            -backend-config="key=${{ env.STATE_KEY_DEPLOYMENT }}" \
         env:
           ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
           ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
           ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
           ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
 
+        # Terraform Version
       - name: Terraform Version
         run: terraform version
 
-      # Destroy Resources In Production
-      - name: Terraform Destroy Production Resources
-        working-directory: environments/production
-        run: terraform destroy -var-file=production.tfvars -var="ssh_public_key_path=${{ secrets.VMSS_SSH_PUBLIC_KEY }}" -auto-approve
+      # Destroy Resources In Deployment
+      - name: Terraform Destroy Deployment Resources
+        working-directory: .
+        run: |
+          terraform destroy \
+          -var-file="${{ env.TFVARS_FILE }}" \
+          -var="ssh_public_key_path=${{ secrets.VMSS_SSH_PUBLIC_KEY }}" \
+          -auto-approve
         env:
           ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
           ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
           ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
           ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
 
+  # Destroy Terraform Deployment Backend Resources
   terraform-destroy-backend:
-    name: Destroy Terraform Production Backend Resources
+    name: Destroy Terraform Deployment Backend Resources
     runs-on: ubuntu-latest
     needs: terraform-destroy-production
 
@@ -96,33 +162,70 @@ jobs:
       - name: Checkout Repo
         uses: actions/checkout@v4
 
-      # Production Backend Variables
-      - name: Load Backend Remote State Variables
+      # Load Backend Variables
+      - name: Determine Backend Variables
         run: |
-          RG=$(grep -E '^\s*resource_group_name\s*=' environments/backend/backend.tfvars | awk -F'=' '{print $2}' | xargs)
-          SA=$(grep -E '^\s*storage_account_name\s*=' environments/backend/backend.tfvars | awk -F'=' '{print $2}' | xargs)
-          CONTAINER=$(grep -E '^\s*storage_container_name\s*=' environments/backend/backend.tfvars | awk -F'=' '{print $2}' | xargs)
-          KEY=$(grep -E '^\s*state_key\s*=' environments/backend/backend.tfvars | awk -F'=' '{print $2}' | xargs)
+          BACKEND_FILE="environments/${ENV}/backend.tfvars"
+            
+          if [ ! -f "$BACKEND_FILE" ]; then
+           echo "Backend TFVARS file not found: $BACKEND_FILE"
+           exit 1
+          fi
 
+            RG=$(grep -E '^resource_group_name' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
+            SA=$(grep -E '^storage_account_name' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
+            CONTAINER=$(grep -E '^storage_container_name' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
+            KEY=$(grep -E '^state_key_backend' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
 
-          RG="${RG//$'\r'/}"
-          SA="${SA//$'\r'/}"
-          CONTAINER="${CONTAINER//$'\r'/}"
-          KEY="${KEY//$'\r'/}"
+            RG="${RG//$'\r'/}"
+            SA="${SA//$'\r'/}"
+            CONTAINER="${CONTAINER//$'\r'/}"
+            KEY="${KEY//$'\r'/}"
 
+            echo "RG_NAME=$RG" >> $GITHUB_ENV
+            echo "STORAGE_ACCOUNT_NAME=$SA" >> $GITHUB_ENV
+            echo "STORAGE_CONTAINER_NAME=$CONTAINER" >> $GITHUB_ENV
+            echo "STATE_KEY_BACKEND=$KEY" >> $GITHUB_ENV
 
-          echo "RG_NAME=$RG" >> $GITHUB_ENV
-          echo "STORAGE_ACCOUNT_NAME=$SA" >> $GITHUB_ENV
-          echo "STORAGE_CONTAINER_NAME=$CONTAINER" >> $GITHUB_ENV
-          echo "STATE_KEY=$KEY" >> $GITHUB_ENV
-
-        # Confirm Production Backend Variables
-      - name: Confirm Backend Variables Values
+      # Set Environment Output
+      - name: Set Environment Output
+        id: set-env
         run: |
-          echo "resource_group_name=$RG_NAME"
-          echo "STORAGE_ACCOUNT_NAME=$STORAGE_ACCOUNT_NAME"
-          echo "STORAGE_CONTAINER_NAME=$STORAGE_CONTAINER_NAME"
-          echo "STATE_KEY=$STATE_KEY"
+          echo "Environment Detected: $ENV"
+          echo "env=${ENV}" >> $GITHUB_OUTPUT
+
+      # Confirm TFVARS exists
+      - name: Confirm TFVARS File
+        run: |
+          if [ ! -f "${{ env.TFVARS_FILE }}" ]; then
+            echo "Unable To Find: ${{ env.TFVARS_FILE }}"
+            exit 1
+          fi
+          echo "Found: ${{ env.TFVARS_FILE }}"
+
+      # Confirm Backend Variables
+      - name: Confirm Backend Variables
+        run: |
+          echo "Resource Group Name       : ${{ env.RG_NAME }}"
+          echo "Storage Account Name      : ${{ env.STORAGE_ACCOUNT_NAME }}"
+          echo "Storage Container Name    : ${{ env.STORAGE_CONTAINER_NAME }}"
+          echo "Terraform Backend State Key : ${{ env.STATE_KEY_BACKEND }}"
+
+      # Clear Cahce
+      - name: Clear Cache
+        run: |
+          echo "Cleaning Cache..."
+
+          rm -rf .terraform
+          rm -f .terraform.lock.hcl
+
+          rm -rf environments/${ENV}/.terraform
+          rm -f environments/${ENV}/.terraform.lock.hcl
+
+          rm -rf environments/backend/bootstrap/.terraform
+          rm -f environments/backend/bootstrap/.terraform.lock.hcl
+
+          echo "Cleanup Complete"
 
         # Azure Authentication
       - name: Azure Authentication
@@ -139,7 +242,7 @@ jobs:
           az storage blob lease break \
             --account-name ${{ env.STORAGE_ACCOUNT_NAME }} \
             --container-name ${{ env.STORAGE_CONTAINER_NAME }} \
-            --blob-name ${{ env.STATE_KEY }} \
+            --blob-name ${{ env.STATE_KEY_BACKEND }} \
           --auth-mode login || echo "No lease present, continuing..."
 
         # Setup Terraform
@@ -156,7 +259,7 @@ jobs:
             -backend-config="resource_group_name=${{ env.RG_NAME }}" \
             -backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" \
             -backend-config="container_name=${{ env.STORAGE_CONTAINER_NAME }}" \
-            -backend-config="key=${{ env.STATE_KEY }}" \
+            -backend-config="key=${{ env.STATE_KEY_BACKEND }}" \
         env:
           ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
           ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
@@ -166,10 +269,13 @@ jobs:
       - name: Terraform Version
         run: terraform version
 
-      # Destroy Resources In Production
+      # Destroy Enviroment Backend Resources
       - name: Terraform Destroy Backend Resources
         working-directory: environments/backend
-        run: terraform destroy -var-file=backend.tfvars -auto-approve -lock=false || echo "Backend Destroyed - Ignoring state Write Error"
+        run: |
+          terraform destroy \
+          -var-file=environments/${ENV}/backend.tfvars -auto-approve \
+          -lock=false || echo "Backend Destroyed - Ignoring State Write Error"
         env:
           ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
           ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
