- Terraform Bootstrap; Changed Determine Env

diff --git a/.github/workflows/terraform-backend-bootstrap.yml b/.github/workflows/terraform-backend-bootstrap.yml
--- a/.github/workflows/terraform-backend-bootstrap.yml
+++ b/.github/workflows/terraform-backend-bootstrap.yml
@@ -17,13 +17,32 @@ jobs:
       - name: Determine Environment From Trigger In Backnd Check
         working-directory: environments/backend/bootstrap
         run: |
-          ENV="${{ github.event.inputs.environment }}"
-          TFVARS_FILE="../../${ENV}/backend.tfvars"
+          if [ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]; then
+             BRANCH="${GITHUB_REF#refs/heads/}"
+           else
+             BRANCH="${{ github.event.workflow_run.head_branch }}"
+           fi
 
-          echo "ENV=$ENV" >> $GITHUB_ENV
-          echo "TFVARS_FILE=$TFVARS_FILE" >> $GITHUB_ENV
-          echo "Using TFVARS File: $TFVARS_FILE"
-          echo "env=$ENV" >> $GITHUB_OUTPUT
+           case "$BRANCH" in
+             dev)
+               ENV="dev"
+               ;;
+             staging)
+               ENV="staging"
+               ;;
+             main)
+               ENV="production"
+               ;;
+             *)
+               echo "Invalid Target Branch: $BRANCH"
+               exit 1
+               ;;
+           esac
+
+           echo "ENV=$ENV" >> $GITHUB_ENV
+           echo "TFVARS_FILE=../../${ENV}/backend.tfvars" >> $GITHUB_ENV
+           echo "Using TFVARS File: ../../${ENV}/backend.tfvars"
+           echo "env=$ENV" >> $GITHUB_OUTPUT
 
       # Confirm Backend TFVARS exists
       - name: Confirm Backend TFVARS File
@@ -32,10 +51,9 @@ jobs:
           ENV="${{ github.event.inputs.environment }}"
           TFVARS_FILE="../../${ENV}/backend.tfvars"
 
-          echo "Using TFVARS File: $TFVARS_FILE"
           if [ ! -f "$TFVARS_FILE" ]; then
-          echo "Backend TFVARS File Missing: $TFVARS_FILE"
-          exit 1
+            echo "Backend TFVARS File Missing: $TFVARS_FILE"
+            exit 1
           fi
           echo "Found Backend TFVARS: $TFVARS_FILE"
 
