- Terraform Infra Deployment; Deployment State Key, Output Confirmations

diff --git a/.github/workflows/terraform-infrastructure-deployment.yml b/.github/workflows/terraform-infrastructure-deployment.yml
--- a/.github/workflows/terraform-infrastructure-deployment.yml
+++ b/.github/workflows/terraform-infrastructure-deployment.yml
@@ -82,10 +82,10 @@ jobs:
       - name: List Module Folders
         run: ls -l Modules/
 
-      # Determine Backend Variables Based On Branch - Using Env TFVARS
-      - name: Determine Variables - Backend Based on Env
+      # Determine Branch Enviroment - Backend Variables For Deployment - Using Backend TFVARS
+      - name: Determine Branch Environment
         run: |
-          BACKEND_FILE="environments/${ENV}/${ENV}.tfvars"
+          BACKEND_FILE="environments/${ENV}/backend.tfvars"
 
           if [ ! -f "$BACKEND_FILE" ]; then
            echo "Backend TFVARS file not found: $BACKEND_FILE"
@@ -95,17 +95,26 @@ jobs:
            RG=$(grep -E '^resource_group_name' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
            SA=$(grep -E '^storage_account_name' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
            CONTAINER=$(grep -E '^storage_container_name' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
-           KEY=$(grep -E '^state_key' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
+           KEY=$(grep -E '^state_key_deployment' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
 
-          RG="${RG//$'\r'/}"
-          SA="${SA//$'\r'/}"
-          CONTAINER="${CONTAINER//$'\r'/}"
-          KEY="${KEY//$'\r'/}"
+           RG="${RG//$'\r'/}"
+           SA="${SA//$'\r'/}"
+           CONTAINER="${CONTAINER//$'\r'/}"
+           KEY="${KEY//$'\r'/}"
 
-          echo "RG_NAME=$RG" >> $GITHUB_ENV
-          echo "STORAGE_ACCOUNT_NAME=$SA" >> $GITHUB_ENV
-          echo "STORAGE_CONTAINER_NAME=$CONTAINER" >> $GITHUB_ENV
-          echo "STATE_KEY=$KEY" >> $GITHUB_ENV
+           echo "RG_NAME=$RG" >> $GITHUB_ENV
+           echo "STORAGE_ACCOUNT_NAME=$SA" >> $GITHUB_ENV
+           echo "STORAGE_CONTAINER_NAME=$CONTAINER" >> $GITHUB_ENV
+           echo "STATE_KEY_DEPLOYMENT=$KEY" >> $GITHUB_ENV
+
+        # Confirm Backend exists
+      - name: Confirm TFVARS File
+        run: |
+          if [ ! -f "${{ env.TFVARS_FILE }}" ]; then
+            echo "Unable To Find: ${{ env.TFVARS_FILE }}"
+            exit 1
+          fi
+          echo "Found: ${{ env.TFVARS_FILE }}"
 
         # Confirm Backend Variables
       - name: Confirm Backend Variables
@@ -113,7 +122,7 @@ jobs:
           echo "Resource Group Name       : ${{ env.RG_NAME }}"
           echo "Storage Account Name      : ${{ env.STORAGE_ACCOUNT_NAME }}"
           echo "Storage Container Name    : ${{ env.STORAGE_CONTAINER_NAME }}"
-          echo "Terraform State Key       : ${{ env.STATE_KEY }}"
+          echo "Terraform Deployment State Key       : ${{ env.STATE_KEY_DEPLOYMENT }}"
 
       # Terraform Init
       - name: Initialize Terraform
@@ -123,7 +132,7 @@ jobs:
             -backend-config="resource_group_name=${{ env.RG_NAME }}" \
             -backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" \
             -backend-config="container_name=${{ env.STORAGE_CONTAINER_NAME }}" \
-            -backend-config="key=${{ env.STATE_KEY }}" \
+            -backend-config="key=${{ env.STATE_KEY_DEPLOYMENT }}" \
         env:
           ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
           ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
